name: Deploy ReactJS, TS, Router and Redux app on Heroku.
description: A ReactJS App with support for TypeScript, React Router and Redux deployed on Heroku.
branding:
  icon: bell # https://feathericons.com/
  color: blue # hex accepted

inputs:                                                  
  - name: API_KEY                                  
    description: Heroku API Key for deployment
  - name: APP_NAME
    description: App Name to be deployed on Heroku (must be unique)
  - name: EMAIL
    description: Heroku Email Id

configs:
  repo-metadata:
    parameters:
      description: 'ReactJS App with TS, Router and Redux deployed on Heroku.'
      secrets: 
      - name: HEROKU_API_KEY
        value: ${{ inputs.API_KEY }}
      - name: HEROKU_APP_NAME
        value: ${{ inputs.APP_NAME }}
      - name: HEROKU_EMAIL
        value: ${{ inputs.EMAIL }}
      topics:
      - reactjs
      - typescript
      - react-router
      - redux
      - heroku

init:
  uses: "setup.yml"